dist: xenial
os: linux

addons:
    apt_packages:
        - lib32z1
        - lib32stdc++6

language: c

env:
  global:
    - SOURCES=$TRAVIS_BUILD_DIR/src
    - SOURCES_SM=$TRAVIS_BUILD_DIR/addons/sourcemod/scripting
    - SOURCES_CORE=$TRAVIS_BUILD_DIR/ccprocessor
    - SOURCES_RIP=$TRAVIS_BUILD_DIR/ripext
    - SOURCES_JANSSON=$TRAVIS_BUILD_DIR/jansson
    - SOURCES_SHOP=$TRAVIS_BUILD_DIR/shop
    - SOURCES_VIP=$TRAVIS_BUILD_DIR/vip
    - SOURCES_LR=$TRAVIS_BUILD_DIR/lr
    - INCLUDES=$TRAVIS_BUILD_DIR/include
  jobs:
    - SMVERSION=1.10

install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
    - git clone -b main https://github.com/rej-clown/ccprocessor.git $SOURCES_CORE
    - git clone -b main https://github.com/rej-clown/sm-jansson.git $SOURCES_JANSSON
    - git clone -b main https://github.com/ErikMinekus/sm-ripext.git $SOURCES_RIP
    - git clone -b master https://github.com/FD-Forks/Shop-Core.git $SOURCES_SHOP
    - git clone -b master https://github.com/R1KO/VIP-Core.git $SOURCES_VIP
    - git clone -b master https://github.com/levelsranks/levels-ranks-core.git $SOURCES_LR

before_script:
    - cp -R -f $INCLUDES $SOURCES_SM
    - cp -R -f $SOURCES_CORE/include $SOURCES_SM
    - cp -R -f $SOURCES_RIP/pawn/scripting/include $SOURCES_SM
    - cp -R -f $SOURCES_JANSSON/pawn/scripting/include $SOURCES_SM
    - cp -R -f $SOURCES_SHOP/addons/sourcemod/scripting/include $SOURCES_SM
    - cp -R -f $SOURCES_VIP/addons/sourcemod/scripting/include $SOURCES_SM
    - cp -R -f $SOURCES_LR/"Game Server"/addons/sourcemod/scripting/include $SOURCES_SM
    - chmod +x $SOURCES_SM/spcomp
    - chmod +x $TRAVIS_BUILD_DIR/travis/compile.sh
    - chmod +x $TRAVIS_BUILD_DIR/travis/package.sh

script: 
  - bash ./travis/compile.sh $SOURCES $SOURCES_SM || exit 1 # ?

before_deploy:
  - bash ./travis/package.sh $SOURCES ${TRAVIS_BUILD_NUMBER} || exit 1

deploy:
  provider: releases
  token:
    secure: PAsLQmiZfhIt6TrKChaNACUKY2e7uLg5A3oZv3crOzfK+EifrFiIpQPdO4lXdfVp4dgQyivYi0e7579pW6eBOlZEioxJw30XNKWFUYKBXAgsDVZJDCdclQYeJM0+HdWQRe4XdePMQfkgaAHCCNflksOTg+PZnb+erhlD9QnWqUAHcy8oD9WLON7Qc3z+oDYBl0nkpjriUd6LbWrMk9UYlZGFu1XBouh/NeQNpLKjtx9HiEQM5T15ICP4QWtFgt2O1SFuXF3i2IP6QsuJmn+46Kl1Xomun0B8kCWSov0srrn16xODBZ6NOBjuiWQk6TLLy/9DdfKROZpieBEcXLBZnbKvIxpvjfxnjQKN6WIxvVgwtRowDQPpiNQQvqR1ZLbdgY4yiC6GCJTbJ9y42N70vW+A8zAE/O3Yk7Dt/QA4v/Tb38A3j9CkapqzIVrXSZbj8oXNavSQ41NvlEIvqYuaSHlPneyzxvOncStJsiX2x5KWwAk1clfKzCTLys1sU8rbjyU57+DFR/diFv3l6grjhPbuhAKdkyhvGMfhMeAfiYiWy5ecTX18Hi7rgAZzZUC2Es2kxqn96STEz3Z2ctMVz4f0ohvvuRX0fLa0at8LLiyimZQiQHJShyc12ttFGCVHQtBAeTdXy0K631HF/4BoIZxAin4USCnjGbH5zTOwP9g=
  file_glob: true
  file: $SOURCES/*
  skip_cleanup: true
  on:
    tags: true

notifications:
    email: false
